package fr.eni.bids.dal.jdbc;

import java.util.ArrayList;
import java.util.LinkedHashMap;

import fr.eni.bids.BidsException;
import fr.eni.bids.bo.Bid;

public class BidJDBCDAOImpl extends GenericJDBCDAOImpl<Bid> {
	public BidJDBCDAOImpl() throws BidsException {
		super();
	}

	@Override
	protected void setIdentifiers() {
		this.identifiers = new ArrayList<>();
		this.identifiers.add("itemId"); // article vendu
		this.identifiers.add("userId"); // enchérisseur
		this.autogeneratedIdentifiers = 0;
	}

	@Override
	protected void setTableName() {
		this.tableName = "BIDS";
	}

	@Override
	protected void setFields() {
		this.fields = new LinkedHashMap<String, String>() {
			{
				put("itemId", "fr.eni.bids.dal.jdbc.ItemJDBCDAOImpl");
				put("userId", "fr.eni.bids.dal.jdbc.UserJDBCDAOImpl");
				put("dateCreated", "LocalDateTime");
				put("amount", "Int");
			}
		};
	}

	protected Bid getObject() {
		return new Bid();
	}
}
