package fr.eni.bids.dal.jdbc;

import java.util.ArrayList;
import java.util.LinkedHashMap;

import fr.eni.bids.BidsException;
import fr.eni.bids.bo.Category;

public class CategoryJDBCDAOImpl extends GenericJDBCDAOImpl<Category> {
	public CategoryJDBCDAOImpl() throws BidsException {
		super();
	}

	@Override
	protected void setIdentifiers() {
		this.identifiers = new ArrayList<>();
		this.identifiers.add("id");
		this.autogeneratedIdentifiers = 1;
	}

	@Override
	protected void setTableName() {
		this.tableName = "BID_ITEM_CATEGORIES";
	}

	@Override
	protected void setFields() {
		this.fields = new LinkedHashMap<String, String>() {
			{
				put("id", "Integer");
				put("libelle", "String");
			}
		};
	}

	@Override
	protected Category getObject() {
		return new Category();
	}
}
