package fr.eni.bids.dal.jdbc;

import java.util.ArrayList;
import java.util.LinkedHashMap;

import fr.eni.bids.BidsException;
import fr.eni.bids.bo.PickUpAdress;

public class PickUpAdressJDBCDAOImpl extends GenericJDBCDAOImpl<PickUpAdress> {
	public PickUpAdressJDBCDAOImpl() throws BidsException {
		super();
	}

	@Override
	protected void setIdentifiers() {
		this.identifiers = new ArrayList<>();
		this.identifiers.add("itemId");
		this.autogeneratedIdentifiers = 0;
	}

	@Override
	protected void setTableName() {
		this.tableName = "BID_ITEM_PICKUP_ADDRESS";
	}

	@Override
	protected void setFields() {
		this.fields = new LinkedHashMap<String, String>() {
			{
				put("itemId", "fr.eni.bids.dal.jdbc.ItemJDBCDAOImpl");
				put("street", "String");
				put("zipCode", "String");
				put("town", "String");
			}
		};
	}

	@Override
	protected PickUpAdress getObject() {
		return new PickUpAdress();
	}
}
