package fr.eni.bids.dal.jdbc;

import java.util.ArrayList;
import java.util.LinkedHashMap;

import fr.eni.bids.BidsException;
import fr.eni.bids.bo.User;

public class UserJDBCDAOImpl extends GenericJDBCDAOImpl<User> {
	public UserJDBCDAOImpl() throws BidsException {
		super();
	}

	@Override
	protected void setIdentifiers() {
		this.identifiers = new ArrayList<>();
		this.identifiers.add("id");
		this.autogeneratedIdentifiers = 1;
	}

	@Override
	protected void setTableName() {
		this.tableName = "USERS";
	}

	@Override
	protected void setFields() {
		this.fields = new LinkedHashMap<String, String>() {
			{
				put("id", "Integer");
				put("pseudo", "String");
				put("name", "String");
				put("firstName", "String");
				put("email", "String");
				put("telephone", "String");
				put("street", "String");
				put("zipCode", "String");
				put("town", "String");
				put("pwd", "String");
				put("credit", "Int");
				put("isAdmin", "Byte");
			}
		};
	}

	protected User getObject() {
		return new User();
	}

}
