USE [master]
GO
/****** Object:  Database [BID]    Script Date: 18/11/2021 15:40:31 ******/
CREATE DATABASE [BID]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BID', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BID.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BID_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\BID_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BID] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BID].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BID] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BID] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BID] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BID] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BID] SET ARITHABORT OFF 
GO
ALTER DATABASE [BID] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BID] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BID] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BID] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BID] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BID] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BID] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BID] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BID] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BID] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BID] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BID] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BID] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BID] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BID] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BID] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BID] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BID] SET RECOVERY FULL 
GO
ALTER DATABASE [BID] SET  MULTI_USER 
GO
ALTER DATABASE [BID] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BID] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BID] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BID] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BID] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'BID', N'ON'
GO
ALTER DATABASE [BID] SET QUERY_STORE = OFF
GO
USE [BID]
GO
/****** Object:  User [userBid]    Script Date: 18/11/2021 15:40:32 ******/
CREATE USER [userBid] FOR LOGIN [userBid] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_datareader] ADD MEMBER [userBid]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [userBid]
GO
/****** Object:  Table [dbo].[BID_ITEM_CATEGORIES]    Script Date: 18/11/2021 15:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BID_ITEM_CATEGORIES](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[libelle] [varchar](30) NOT NULL,
 CONSTRAINT [PK_BID_ITEM_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BID_ITEM_PICKUP_ADDRESS]    Script Date: 18/11/2021 15:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BID_ITEM_PICKUP_ADDRESS](
	[itemId] [int] NOT NULL,
	[street] [varchar](30) NOT NULL,
	[zipCode] [varchar](10) NOT NULL,
	[town] [varchar](40) NOT NULL,
 CONSTRAINT [PK_BID_ITEM_PICKUP_ADDRESS] PRIMARY KEY CLUSTERED 
(
	[itemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BID_ITEMS]    Script Date: 18/11/2021 15:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BID_ITEMS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[name] [varchar](30) NOT NULL,
	[description] [varchar](300) NOT NULL,
	[dateStart] [date] NOT NULL,
	[dateEnd] [date] NOT NULL,
	[priceSeller] [int] NULL,
	[priceBuyer] [int] NULL,
	[userIdBuyer] [int] NOT NULL,
	[cateId] [int] NOT NULL,
 CONSTRAINT [PK_BID_ITEMS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[BIDS]    Script Date: 18/11/2021 15:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BIDS](
	[userId] [int] NOT NULL,
	[itemId] [int] NOT NULL,
	[dateCreated] [datetime] NOT NULL,
	[amount] [int] NOT NULL,
 CONSTRAINT [PK_BIDS] PRIMARY KEY CLUSTERED 
(
	[userId] ASC,
	[itemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[USERS]    Script Date: 18/11/2021 15:40:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USERS](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[pseudo] [varchar](30) NOT NULL,
	[name] [varchar](30) NOT NULL,
	[firstName] [varchar](30) NOT NULL,
	[email] [varchar](40) NOT NULL,
	[telephone] [varchar](15) NULL,
	[street] [varchar](30) NOT NULL,
	[zipCode] [varchar](10) NOT NULL,
	[town] [varchar](40) NOT NULL,
	[pwd] [varchar](50) NOT NULL,
	[credit] [int] NOT NULL,
	[isAdmin] [bit] NOT NULL,
 CONSTRAINT [PK_USERS] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BID_ITEMS] ADD  DEFAULT (getdate()) FOR [dateStart]
GO
ALTER TABLE [dbo].[BID_ITEMS] ADD  DEFAULT (getdate()+(90)) FOR [dateEnd]
GO
ALTER TABLE [dbo].[BIDS] ADD  DEFAULT (getdate()) FOR [dateCreated]
GO
ALTER TABLE [dbo].[BIDS] ADD  DEFAULT ((0)) FOR [amount]
GO
ALTER TABLE [dbo].[USERS] ADD  DEFAULT ((0)) FOR [isAdmin]
GO
ALTER TABLE [dbo].[BID_ITEM_PICKUP_ADDRESS]  WITH CHECK ADD  CONSTRAINT [FK_BID_ITEM_PICKUP_ADDRESS_BID_ITEMS] FOREIGN KEY([itemId])
REFERENCES [dbo].[BID_ITEMS] ([id])
GO
ALTER TABLE [dbo].[BID_ITEM_PICKUP_ADDRESS] CHECK CONSTRAINT [FK_BID_ITEM_PICKUP_ADDRESS_BID_ITEMS]
GO
ALTER TABLE [dbo].[BID_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_BID_ITEMS_BID_ITEM_CATEGORIES] FOREIGN KEY([cateId])
REFERENCES [dbo].[BID_ITEM_CATEGORIES] ([id])
GO
ALTER TABLE [dbo].[BID_ITEMS] CHECK CONSTRAINT [FK_BID_ITEMS_BID_ITEM_CATEGORIES]
GO
ALTER TABLE [dbo].[BID_ITEMS]  WITH CHECK ADD  CONSTRAINT [FK_BID_ITEMS_USERS_BUYER] FOREIGN KEY([userIdBuyer])
REFERENCES [dbo].[USERS] ([id])
GO
ALTER TABLE [dbo].[BID_ITEMS] CHECK CONSTRAINT [FK_BID_ITEMS_USERS_BUYER]
GO
ALTER TABLE [dbo].[BIDS]  WITH CHECK ADD  CONSTRAINT [FK_BIDS_BID_ITEMS] FOREIGN KEY([itemId])
REFERENCES [dbo].[BID_ITEMS] ([id])
GO
ALTER TABLE [dbo].[BIDS] CHECK CONSTRAINT [FK_BIDS_BID_ITEMS]
GO
ALTER TABLE [dbo].[BIDS]  WITH CHECK ADD  CONSTRAINT [FK_BIDS_USERS] FOREIGN KEY([userId])
REFERENCES [dbo].[USERS] ([id])
GO
ALTER TABLE [dbo].[BIDS] CHECK CONSTRAINT [FK_BIDS_USERS]
GO
USE [master]
GO
ALTER DATABASE [BID] SET  READ_WRITE 
GO
